version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ng_database
    ports:
      - '5432:5432'
  web:
    image: node
    depends_on:
      - db
    ports:
      - '4000:4000'